use_frameworks!

platform :ios, '8.0'

target 'WGArrayTool_Example' do
  pod 'WGArrayTool', :path => '../'

  target 'WGArrayTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
